### PR TITLE
Update tests to reflect most recent changes in codebase.

### PR DESCRIPTION
**Pull request by kbs5280**
This PR is to fix the 2 broken tests 1605 inherited from 1603.

There are 2 changes in `header-test.js`
The first change is in line 14 and corresponds to the link added in Header.js line 16 where the link `Trends` was added.
The second change is in line 24 and corresponds to Header.js lines 11-20.

You can run the test suite for the front end to verify it is working `npm run test`

### CODE REVIEW

**Comment by Automatic365** [comment]
This changes are straightforward enough. Just updating expectations, right?

**Comment by MsJennyGiraffe** [comment]
Do you know what happened that caused the link length to change from 1 to 2?

**Comment by GSmes** [comment]
@MsJennyGiraffe @zackforbing 
They initially only had the `Looking For` link in the header, which is what was reflected in the test. They then added the 2nd link (`Trends`) to the header, but never updated the test to reflect the change.

**I believe this can be merged if everyone else agrees**

**Comment by kbs5280** [comment]
@MsJennyGiraffe @GSmes is correct. I probably should have noted those details in the PR, but yes, both of the changes were made in the code, but the tests were not updated: The header now has 2 elements. Also, the <div> was restructured slightly.

**Comment by zackforbing** [comment]
yeah, this looks fairly straightforward after hearing it explained. I'm going to go ahead and merge this. I think enough of us have seen it.

**Pull request merged**
