### PR TITLE
[WIP] Style updating

### PR DESCRIPTION
**Pull request by brianrip**
Most importantly, this PR addresses this misalignment of columns on the job index and show views. 

I changed some font sizes and colors - I like the grey tones but open to some flare if requested. 

@ksk5280 @cheljoh @natevenn

### CODE REVIEW

**Comment by natevenn** [comment]
Right now most of the site is white and grey. I dont mind the grey but some color would be nice. Im not the one to say what color though. Maybe some blue borders and text????

**Comment by brianrip** [comment]
I am playing with some color now. Update coming... Hold tight!

**Comment by brianrip** [comment]
Updated with colors and improved alignment. Check it out. @natevenn @ksk5280 @cheljoh

**Comment by natevenn** [comment]
That looks really good @brianrip. Nice work. I will leave this up until the rest of the group sees the styling and if they want to make comments. We should tag Louisa and have her look at it and give feedback. I really like the color contrasts you chose.

**Comment by ksk5280** [comment]
Brian, I think the style changes look great! I'm going to pull down this branch and try moving around a few things for organization/UX purposes.

**Comment by cheljoh** [comment]
I like the new color scheme, nice job @ksk5280  and @brianrip! I would like to have fixed div heights for each job listing div and more of a margin on the sides of the divs.

**Comment by natevenn** [comment]
styling update pr is not on a different branch and will be merged in from the other branch.

**Pull request closed without merging**
