### PR TITLE
31 search by tech stack

### LINKED ISSUE #31: Search by tech stack
As a user
When I view all jobs
And I click a link on the side bar for a specific technology
Then I only see jobs listed that match selected technology

### PR DESCRIPTION
**Pull request by cheljoh**
@ksk5280 @brianrip @natevenn 

Users can now search by tech stack OR location. The tech stack is limited to:
Ruby
Rails
Javascript
React
Go
Ember
Clojure
Angular
Python

Was trying to scope by recent_jobs when receiving a search query response from the API (response.recent_jobs), but realized it did not display correctly when the search query yielded no response.

Closes #31

### CODE REVIEW

**Comment by natevenn** [comment]
@cheljoh this branch looks good. Let me know if you are ready to merge it in

**Comment by ksk5280** [comment]
@cheljoh what do you think about implementing the tech stack as a dropdown menu the way Brian had done previously? It's nice to be able to search by location and technology at the same time, but the only downside is that the user doesn't know what tech stacks they can search for.

**Comment by cheljoh** [comment]
Yeah I thought about that, one easy fix is to just list them below the
search bar...not super great though. We could have a drop down next to
search bar but it would require some reconfiguring and we don't have a ton
of time

**Comment by brianrip** [comment]
I like search bar approach but if the list of available technologies is more than 10. Otherwise we could bring back the drop down. The idea behind implementing the search bar is that the list of available technologies would be dynamically generated from the API and it would prevent leaving out available or new tech stacks. @cheljoh @ksk5280 Looks like everyone has had a chance to see this. Looks great! Lets write up a new issue after we discuss the pros and cons of search bar vs. drop down.

**Pull request merged**
